icons_format = "{icon}"

[theme]
theme = "plain"
[theme.overrides]
good_bg = "#1a1b26"
good_fg = "#a9b1d6"
idle_bg = "#1a1b26"
idle_fg = "#a9b1d6"
warning_bg = "#1a1b26"
critical_bg = "#1a1b26"
info_bg = "#1a1b26"
separator_bg = "#1a1b26"
separator_fg = "#a9b1d6"

[icons]
icons = "awesome4"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "cpu"
# info_cpu = 20
# warning_cpu = 50
# critical_cpu = 90

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "

